### ISSUE TITLE
不用docker如何运行

### ISSUE THREAD

**Issue by yuanhuikai** [swimmingwhale/living-mongo#2]
你好，我对php不是很熟悉，目前想做一个mongo gui工具，请问一下这个代码如何用php来运行啊? 能否在readme中介绍一下。

**Comment by swimmingwhale** [comment]
hi,我在readme中大概写了一些windows下的安装步骤,更详细的步骤可以google一下哦

**Comment by yuanhuikai** [comment]
嗯，好的，谢谢。
